### ISSUE TITLE
El Capitan Change -- Non-Apple Libraries should NOT be placed in /usr/lib

### ISSUE THREAD

**Issue by RobK88** [BoxOfSnoo/Fairmount#4]
With El Capitan, Apple no longer recommends that non-Apple libraries (like libdvdcss.2.dylib) be placed in /usr/lib.

Apple recommends that non Apple libraries be placed in /usr/local/lib.

System Integrity Protection in El Capitan also prevents one from installing anything into /usr/lib (unless you disable SIP via Recovery Partition).  SIP does NOT prevent anyone from installing libraries into /usr/local/lib

P.S.  Handbrake also looks for libdvdcss.2.dylib in /usr/local/lib

Recommended fix:  Change Fairmount so it looks for libdvdcss.2.dylib in /usr/local/lib in addition to the locations already looked at (like /usr/lib etc).

**Comment by pmetzger** [comment]
Care to supply a patch?

**Comment by tomhoover** [comment]
I forked the code to create a patch for the El Captan SIP change, but found there's already a mechanism built into Fairmount to look for libdvdcss* in a different location. The following commands assume you've already installed libdvdcss into /usr/local/lib (using homebrew or by manually copying the file(s)). Simply type open a terminal and type the following commands:

    mkdir ~/Library/Application\ Support/Fairmount
    chdir ~/Library/Application\ Support/Fairmount
    ln -s /usr/local/lib/libdvdcss.* .
    ls -l  # to verify the symlinks were created

**Comment by ayresm** [comment]
Hi - afraid I'm no developer, but when I run these commands I get the following error on the second chdir command:

-bash: chdir: command not found

Anything obvious that I'm doing wrong?

**Comment by tomhoover** [comment]
Try cd instead of chdir.

**Comment by ayresm** [comment]
That worked thanks.  Unfortunately still can't seem to get Fairmount to open in El Capitan.

**Comment by tomhoover** [comment]
Did the symlinks get created properly? What was the output of the final "ls -l" command?

**Comment by ayresm** [comment]
Hi - this is the output I get.  Thanks for your help.

MAMBP:~ Home$ mkdir ~/Library/Application\ Support/Fairmount
mkdir: /Users/Home/Library/Application Support/Fairmount: File exists
MAMBP:~ Home$ cd ~/Library/Application\ Support/Fairmount
MAMBP:Fairmount Home$ ln -s /usr/local/lib/libdvdcss.* .
ln: ./libdvdcss.2.dylib: File exists
MAMBP:Fairmount Home$ ls -l  # to verify the symlinks were created
total 88
-rw-r--r--@ 1 Home  staff  41120 12 Apr  2011 libdvdcss.2.dylib

**Comment by tomhoover** [comment]
This line:

    -rw-r--r--@ 1 Home staff 41120 12 Apr 2011 libdvdcss.2.dylib

indicates that a symlink wasn't created--that is an actual file. "ls -l" should return a line that looks like this:

    lrwxr-xr-x  1 tom  staff  32 Feb  6 10:34 libdvdcss.2.dylib -> /usr/local/lib/libdvdcss.2.dylib

The first character should be a lowercase "L", indicating a link. You should also see the filename to which the link is pointing (after the ->).

To correct, manually delete the "libdvdcss.2.dylib" file from your "~/Library/Application\ Support/Fairmount" directory. Then, type the following commands:

    cd ~/Library/Application\ Support/Fairmount
    ln -s /usr/local/lib/libdvdcss.2.dylib .
    ls -l

and let me know what happens.

BTW- are you running the latest version of Fairmount?

**Comment by ayresm** [comment]
Fantastic!  That worked.  Thanks for your help.  And to confirm I was using version 1.1.3

**Comment by BoxOfSnoo** [comment]
I should check my notifications more often!  Thanks for your comments.  I changed the search path so it won't look at all at /usr/lib.  I may try to see if I can just add to the search list instead of replacing it altogether.  You can also put the library in /opt/local/lib from what I read.
