### ISSUE TITLE
os x 10.11.6

### ISSUE THREAD

**Issue by bob5731** [BoxOfSnoo/Fairmount#8]
How do I build it for os x 10.11.6
<img width="522" alt="7975c9de-d254-11e5-9efa-93c5c99798fb" src="https://user-images.githubusercontent.com/16548974/34856041-afd8046c-f708-11e7-92dc-028e18313c0e.png">

**Comment by pmetzger** [comment]
You need to get the library in question as explained in the instructions.

**Comment by bob5731** [comment]
did it.

**Comment by pmetzger** [comment]
You are not providing enough information here to allow someone to help you.

I suggest reading this:
https://www.chiark.greenend.org.uk/~sgtatham/bugs.html

**Comment by bob5731** [comment]
I put the file ware they need to go. It keep asking for libdvdcss.2.dylib.
Can you add dialog box to find the path to the file.

With El Capitan, Apple no longer recommends that non-Apple libraries (like libdvdcss.2.dylib) be placed in /usr/lib.

Apple recommends that non Apple libraries be placed in /usr/local/lib.

System Integrity Protection in El Capitan also prevents one from installing anything into /usr/lib (unless you disable SIP via Recovery Partition). SIP does NOT prevent anyone from installing libraries into /usr/local/lib

P.S. Handbrake also looks for libdvdcss.2.dylib in /usr/local/lib

Recommended fix: Change Fairmount so it looks for libdvdcss.2.dylib in /usr/local/lib in addition to the locations already looked at (like /usr/lib etc).

**Comment by pmetzger** [comment]
It already looks in /usr/local/lib.

**Comment by bob5731** [comment]
how to I fix it?

**Comment by pmetzger** [comment]
I gave you a URL above. Please read it carefully and follow the directions on how to file good bug reports. I will then have enough information to help you. Right now I have insufficient information to assist effectively.

**Comment by BoxOfSnoo** [comment]
Check out [this issue](https://github.com/BoxOfSnoo/Fairmount/issues/4), you probably don't have the library copied correctly to the right path.

**Comment by bob5731** [comment]
I have looked at that and put the necessary files were they need to be in still get the same error message I can take screenshots of where the files or if need be

**Comment by bob5731** [comment]
Well could you add a dialog box so I can point to the File in question and it will automatically save the past

**Comment by pmetzger** [comment]
@bob5731 You don't seem to be willing to give us enough assistance to be able to help you. If you aren't going to cooperate there isn't much we can do. I sent you that link above for a good reason — it explains how to give a bug report sufficiently detailed and useful that the maintainers of a software package can try to help you fixing your problem.

Repeating it is:
https://www.chiark.greenend.org.uk/~sgtatham/bugs.html
Please read it before sending anything else on this topic.

It is impossible to try to figure out your problem without much more information than you have given us, and repeated requests that you give more information have failed. You are being far too vague. We are not psychics, and are not in a position to extract the information remotely from your mind, so if you won't give us the information we need, we can't help.

I am happy to help, but there's nothing more I can personally do.

**Comment by bob5731** [comment]
I gave you all the goddamn information you need I told you that I put all the fucking files where they need to fucking go your piece of shit program does not seem to give a fuck about where I put the damn files.   By the way I am running Mac OS X 10.11.6   When I try to compile from  source code it tells me I need OS X 10.12  or above.  So the problem is that your program doesn’t know how to look for the files in appropriate place or the version that you have on github is broke.  I’m create a file folder in my library called application\support\Fairmount  instructor necessary files in there. less I’m using the wrong version  of the  file. Fix the download link in the program to download the correct file.  Like I said in my last post add a dialog box so that we can easily add the file to the  program.

**Comment by BoxOfSnoo** [comment]
This discussion is not constructive.  If we weren't helpful, sorry.

**Comment by bob5731** [comment]
Hi

**Comment by bob5731** [comment]
Are you going to look at the bugs   Where I mentioned or not?
